export default [
  {
    title: 'Redes Sociais',
    description: 'Conteúdo e consistência para crescer sua presença online.',
    price: 'R$ 890',
    originalPrice: 'R$ 1.090',
    cadence: '/mês',
    icon: 'lucide:share-2',
    badge: 'Mais escolhido',
    features: [
      'Planejamento mensal',
      'Artes e legendas',
      'Calendário de posts',
      'Acompanhamento de métricas',
    ],
  },
  {
    title: 'Marketing Digital',
    description: 'Estratégia para aumentar visibilidade e gerar leads.',
    price: 'R$ 1.290',
    originalPrice: 'R$ 1.590',
    cadence: '/mês',
    icon: 'lucide:trending-up',
    badge: 'Para escalar',
    highlight: true,
    features: [
      'Estratégia e funil',
      'Campanhas e otimizações',
      'Relatório mensal',
      'Suporte dedicado',
    ],
  },
  {
    title: 'Criação de Sites',
    description: 'Site moderno, responsivo e otimizado para conversão.',
    price: 'R$ 1.490',
    originalPrice: 'R$ 1.890',
    cadence: 'por projeto',
    icon: 'lucide:globe',
    badge: 'Ideal para começar',
    features: ['Layout personalizado', 'SEO básico', 'Formulário de contato', 'Entrega rápida'],
  },
];
